sudo: required

services: docker

before_install:
  - docker login -u xunipero -p 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
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test



